# global
debug: false
admin: []

# api
api_root: http://localhost:8080
auth_key: REPLACE_IT
qq: 123456

# receiver
ping_timeout: 5
sleep_time: 3

# command
prefix:
  - /
  - 、

# db
mongo:
  host: db
  port: 27017
  username:
  password:
  db: bot

# plugins
plugins:
  - common
  - admin
