version: '3'

services:

  cqhttp:
    image: richardchien/cqhttp:latest
    ports:
      - 9000:9000
    restart: unless-stopped
    environment:
      VNC_PASSWD: 12345678
      COOLQ_ACCOUNT: 3163316758
      FORCE_ENV: "true"
      CQHTTP_USE_HTTP: "false"
      CQHTTP_USE_WS: "false"
      CQHTTP_USE_WS_REVERSE: "true"
      CQHTTP_WS_REVERSE_API_URL: ws://signal_bot:8080/ws/api/
      CQHTTP_WS_REVERSE_EVENT_URL: ws://signal_bot:8080/ws/event/

  signal_bot:
    build: .
    restart: unless-stopped
    environment:
      TZ: "Asia/Shanghai"